"""Agregar columna estado a solicitud_visita

Revision ID: f96709933dbc
Revises: 
Create Date: 2025-05-15 22:33:43.456304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96709933dbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_visita', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
